"""team_digest.py — emit briefings/_team.md after all 5 briefings build.

Spec 084 Task 3.4 / AC9.

One line per advisor (~100 tokens total, ~500 token budget for 5 lines):
  | advisor | status | queue | p0 | last-session |

`team.quorum` Step 1 loads _team.md instead of all 5 full briefings,
shrinking first-turn input by ≥60%.

Entry point:
  python3 -m briefing.team_digest          # all 5 advisors
  python3 -m briefing.team_digest [adv…]   # specific advisors only
"""
from __future__ import annotations

import re
import sys
import time
from datetime import UTC, datetime
from pathlib import Path

from briefing.paths import (
    briefings_dir,
    gh_cache_dir,
    sessions_dir,
)
from briefing.scans._gh_cache import read_gh_cache
from enginelib.advisors import known_advisors


def _default_advisors(root: Path | None = None) -> tuple[str, ...]:
    """Digest advisor set: derived from the .claude/agents registry (#47), never a
    hardcoded roster tuple. Empty when the registry is absent (colocated / test
    envs) so a Conclave instance digests exactly its own hired roster. `root`
    defaults to repo_root(); tests inject it to avoid the module-cached resolver."""
    from briefing.paths import repo_root
    try:
        base = root if root is not None else repo_root()
    except RuntimeError:
        return ()
    return tuple(sorted(known_advisors(base)))

# Regex to extract generated_at from briefing HTML comment.
_GENERATED_AT_RE = re.compile(r"<!-- generated_at: ([^\s>]+)")


def _briefing_status(briefing_path: Path) -> str:
    """Return 'fresh' / 'stale (Nd)' / 'missing' based on briefing mtime."""
    if not briefing_path.is_file():
        return "missing"
    age_s = int(time.time() - briefing_path.stat().st_mtime)
    age_h = age_s // 3600
    if age_h < 24:
        return "fresh"
    age_d = age_h // 24
    return f"stale ({age_d}d)"


def _queue_count(advisor: str) -> int:
    """Return number of open GH issues from gh-cache (0 on miss)."""
    cache_path = gh_cache_dir() / f"{advisor}.md"
    rows = read_gh_cache(cache_path, advisor=advisor)
    return len(rows)


def _p0_count(advisor: str) -> int:
    """Return number of p0 issues from gh-cache (0 on miss)."""
    cache_path = gh_cache_dir() / f"{advisor}.md"
    rows = read_gh_cache(cache_path, advisor=advisor)
    return sum(1 for row in rows if "p0" in row)


def _last_session(advisor: str) -> str:
    """Return stem of most-recent session file, or '—'."""
    sess_dir = sessions_dir()
    if not sess_dir.is_dir():
        return "—"
    pattern = f"*-{advisor}-*.md"
    matches = list(sess_dir.glob(pattern))
    if not matches:
        return "—"
    stem = sorted((f.stem for f in matches), reverse=True)[0]
    # Strip date prefix for brevity: YYYY-MM-DD-<advisor>-<slug> → <slug>
    parts = stem.split(f"-{advisor}-", 1)
    slug = parts[1] if len(parts) > 1 else stem
    return slug[:40]  # cap at 40 chars


def _digest_line(advisor: str) -> str:
    """Return a single pipe-delimited table row for one advisor."""
    briefing_path = briefings_dir() / f"{advisor}.md"
    status = _briefing_status(briefing_path)
    queue = _queue_count(advisor)
    p0 = _p0_count(advisor)
    last = _last_session(advisor)
    return f"| {advisor:<12} | {status:<12} | {queue:>5} | {p0:>2} | {last} |"


def build_team_md(advisors: tuple[str, ...] | None = None) -> str:
    """Return the full _team.md content as a string."""
    if advisors is None:
        advisors = _default_advisors()
    now = datetime.now(tz=UTC).astimezone().strftime("%Y-%m-%dT%H:%M:%S%z")
    header = (
        f"<!-- AUTO-GENERATED by engine briefing team-digest — DO NOT EDIT -->\n"
        f"<!-- generated_at: {now} -->\n"
        f"<!-- regen: python -m engine briefing team-digest -->\n\n"
        f"# Team digest\n\n"
        f"> One-line status per advisor. Load this instead of all 5 full briefings.\n"
        f"> Full briefing: `agent-memory/advisors/briefings/<advisor>.md`\n\n"
        f"| advisor       | status       | queue |  p0 | last session |\n"
        f"|:--------------|:-------------|------:|----:|:-------------|\n"
    )
    lines = [_digest_line(adv) for adv in advisors]
    return header + "\n".join(lines) + "\n"


def write_team_md(advisors: tuple[str, ...] | None = None) -> Path:
    """Build and atomically write briefings/_team.md. Returns the path."""
    import os
    import tempfile

    if advisors is None:
        advisors = _default_advisors()

    out_dir = briefings_dir()
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "_team.md"

    content = build_team_md(advisors)

    fd, tmp = tempfile.mkstemp(dir=out_dir, prefix=".team-digest-tmp-")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(content)
        os.replace(tmp, out_path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise

    return out_path


def main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(
        prog="briefing.team_digest",
        description="Emit briefings/_team.md (one line per advisor).",
    )
    parser.add_argument(
        "advisors",
        nargs="*",
        metavar="advisor",
        help="Canonical advisor names (default: all 5).",
    )
    args = parser.parse_args(argv)

    valid = _default_advisors()
    targets: tuple[str, ...] = tuple(args.advisors) if args.advisors else valid
    for adv in targets:
        if valid and adv not in valid:
            print(f"team_digest: unknown advisor: {adv}", file=sys.stderr)
            return 1

    out_path = write_team_md(targets)
    print(f"[team-digest] wrote={out_path}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
