"""project.py — the COMPUTED-DUTIES.md projection (spec 091 §3).

Composes the engine base with one agent's self-written manifest and duty files, and renders
a COMPACT list: one `duty_id: description` line each. Never bodies, never YAML.

That constraint is the design, not a formatting preference. The projection is injected for
every holder on every session; the bodies lazy-load only when a duty triggers. A projection
that grows bodies still functions — it just silently charges every session for text the
progressive-disclosure design exists to defer.

I/O here is reads only (duty files off disk). Writing the projection is the adapter's job.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from enginelib.duties.duty import Duty, load_duty
from enginelib.duties.model import Manifest, Norm
from enginelib.duties.validate import Finding, compose


@dataclass
class Projection:
    agent_id: str
    norms: list[Norm] = field(default_factory=list)
    duties: list[Duty] = field(default_factory=list)
    findings: list[Finding] = field(default_factory=list)


def project_agent(
    base: Manifest,
    agent_manifest: Manifest,
    agent_id: str,
    duties_dir: Path,
) -> Projection:
    """Compose base + agent and collect the agent's duty files.

    A duty carrying findings is still projected. Refusing to render it would hide every
    other duty the agent holds behind one bad file — the opposite of surfacing the problem.
    """
    composed = compose([base, agent_manifest])
    duties: list[Duty] = []
    findings: list[Finding] = []

    if duties_dir.is_dir():
        for path in sorted(duties_dir.glob("*.md")):
            duty = load_duty(path)
            duties.append(duty)
            findings.extend(duty.findings)

    duties.sort(key=lambda d: d.id)
    return Projection(
        agent_id=agent_id,
        norms=composed.for_role(agent_id),
        duties=duties,
        findings=findings,
    )


def render_projection(agent_id: str, projection: Projection) -> str:
    """Render COMPUTED-DUTIES.md. Generated artifact — never hand-edited."""
    lines = [
        f"# COMPUTED-DUTIES — {agent_id}",
        "",
        "> Generated by `engine duty project` (spec 091 §3). Do not hand-edit.",
        "> One line per duty: the description only. Bodies lazy-load when a duty triggers.",
        "",
        "## Duties",
        "",
    ]

    if projection.duties:
        for duty in projection.duties:
            lines.append(f"{duty.id}: {duty.description}")
    else:
        lines.append("_none — this agent has written no duties yet._")

    lines += ["", "## Norms in force", ""]
    if projection.norms:
        for norm in projection.norms:
            condition = f" when {norm.condition}" if norm.condition else ""
            lines.append(f"{norm.type}: {norm.mission}{condition}")
    else:
        lines.append("_none_")

    if projection.findings:
        lines += ["", "## Findings", ""]
        lines += [f"{f.severity}: {f.code} — {f.message}" for f in projection.findings]

    return "\n".join(lines).rstrip() + "\n"
