"""project.py — the COMPUTED-DUTIES.md projection (spec 091 §3).

Composes the engine base with one agent's self-written manifest and duty files, and renders
a COMPACT list: one `duty_id: description` line each. Never bodies, never YAML.

That constraint is the design, not a formatting preference. The projection is injected for
every holder on every session; the bodies lazy-load only when a duty triggers. A projection
that grows bodies still functions — it just silently charges every session for text the
progressive-disclosure design exists to defer.

I/O here is reads only (duty files off disk). Writing the projection is the adapter's job.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from enginelib.duties.derive import derive, load_duties
from enginelib.duties.duty import Duty
from enginelib.duties.model import AgentKind, Manifest, Norm
from enginelib.duties.validate import Finding, compose


@dataclass
class Projection:
    agent_id: str
    norms: list[Norm] = field(default_factory=list)
    duties: list[Duty] = field(default_factory=list)
    findings: list[Finding] = field(default_factory=list)
    derived: Manifest = field(default_factory=lambda: Manifest(version=1))
    """What the agent's duty files contributed to the namespace. Carried out so the caller
    can validate against the SAME derivation the projection composed — deriving a second
    time beside the call is how the registry starts showing one thing and enforcing another."""


def project_agent(
    base: Manifest,
    agent_manifest: Manifest,
    agent_id: str,
    duties_dir: Path,
    kind: AgentKind = "advisor",
) -> Projection:
    """Compose base + agent + the norms derived from the agent's own duty files.

    A duty carrying findings is still projected. Refusing to render it would hide every
    other duty the agent holds behind one bad file — the opposite of surfacing the problem.

    Derivation is composed in here rather than beside here: `check_discharge` composes the
    same three, so what the projection shows and what the check enforces cannot diverge.
    """
    duties = load_duties(duties_dir)
    findings: list[Finding] = [f for duty in duties for f in duty.findings]
    derived = derive(duties, agent_id, kind)
    composed = compose([base, agent_manifest, derived])

    return Projection(
        agent_id=agent_id,
        norms=composed.for_role(agent_id),
        duties=duties,
        findings=findings,
        derived=derived,
    )


def render_projection(agent_id: str, projection: Projection) -> str:
    """Render COMPUTED-DUTIES.md. Generated artifact — never hand-edited."""
    lines = [
        f"# COMPUTED-DUTIES — {agent_id}",
        "",
        "> Generated by `engine duty project` (spec 091 §3). Do not hand-edit.",
        "> One line per duty: the description only. Bodies lazy-load when a duty triggers.",
        "",
        "## Duties",
        "",
    ]

    if projection.duties:
        force = {n.mission: n.type for n in projection.norms}
        for duty in projection.duties:
            # Composed force, not declared force — a duty cannot declare its own (P2 §0), so
            # this tag is the only place the reader learns whether the duty is actually owed.
            # `advice` is the floor: every duty derives one, so the lookup cannot miss.
            lines.append(f"{duty.id} [{force.get(duty.mission, 'advice')}]: {duty.description}")
    else:
        lines.append("_none — this agent has written no duties yet._")

    lines += ["", "## Norms in force", ""]
    if projection.norms:
        for norm in projection.norms:
            condition = f" when {norm.condition}" if norm.condition else ""
            lines.append(f"{norm.type}: {norm.mission}{condition}")
    else:
        lines.append("_none_")

    if projection.findings:
        lines += ["", "## Findings", ""]
        lines += [f"{f.severity}: {f.code} — {f.message}" for f in projection.findings]

    return "\n".join(lines).rstrip() + "\n"
