"""enginelib/memory/index.py — rebuild advisors/INDEX.md.

Port of memory-index.sh. I/O-free of stdout/argparse/sys.exit (file I/O + clock OK).
Never commits git. Returns the written INDEX.md path.
"""
from __future__ import annotations

import re
from collections import defaultdict
from datetime import date as _date_cls
from pathlib import Path

from enginelib import paths
from enginelib.frontmatter import fm_get
from enginelib.snapshot import snapshot_write


def rebuild(now: str) -> Path:
    """Rebuild advisors/INDEX.md for the given date string (YYYY-MM-DD).

    Raises ValueError if `now` cannot be parsed as a YYYY-MM-DD date.
    """
    try:
        now_date = _date_cls.fromisoformat(now)
    except ValueError:
        raise ValueError(f"unable to parse --now: {now}") from None

    mem_root = paths.advisors_memory_dir()
    paths.ensure_dir(mem_root)
    out = mem_root / "INDEX.md"

    parts: list[str] = []

    # --- Header ---
    # Deviation (justified): bash header says "memory-index.sh" which is deleted in this
    # commit. Freshened to "engine memory index" so the generated file does not name a
    # deleted script. No bats case asserts this header text.
    parts.append("# Advisor Memory Index\n")
    parts.append("\n")
    parts.append("> Auto-generated by `engine memory index`. Do not edit.\n")
    parts.append(f"> Last regenerated: {now}\n")
    parts.append("\n")

    # --- Recent decisions (sorted DESC by basename = date-desc) ---
    parts.append("## Recent decisions\n")
    parts.append("\n")
    dec_dir = paths.decisions_dir()
    dec_files = (
        sorted(dec_dir.glob("*.md"), key=lambda f: f.stem, reverse=True)
        if dec_dir.is_dir()
        else []
    )
    if dec_files:
        for f in dec_files:
            base = f.stem
            parts.append(f"- [{base}](decisions/{base}.md)\n")
    else:
        parts.append("- _(none)_\n")
    parts.append("\n")

    # --- Sessions grouped by advisor (advisor ASC, basename DESC within group) ---
    parts.append("## Recent sessions by advisor\n")
    parts.append("\n")
    sess_dir = paths.sessions_dir()
    sess_files = list(sess_dir.glob("*.md")) if sess_dir.is_dir() else []
    if sess_files:
        # Two-pass stable sort: basename DESC first, then advisor ASC (mirrors bash sort -t'|' -k1,1 -k2,2r)
        sess_pairs = [(fm_get(f, "advisor") or "unknown", f.stem) for f in sess_files]
        sess_pairs.sort(key=lambda x: x[1], reverse=True)   # basename DESC (stable)
        sess_pairs.sort(key=lambda x: x[0])                  # advisor ASC (stable)

        current_adv = ""
        for adv, base in sess_pairs:
            if adv != current_adv:
                if current_adv:          # close previous group with blank line
                    parts.append("\n")
                parts.append(f"### {adv}\n")
                parts.append("\n")
                current_adv = adv
            parts.append(f"- [{base}](sessions/{base}.md)\n")
        parts.append("\n")              # trailing blank line after last group
    else:
        parts.append("- _(none)_\n")
        parts.append("\n")

    # --- Walk open mentions ONCE: gather counts + stale list ---
    ment_root = paths.mentions_dir()
    open_files = list(ment_root.glob("*/open/*.md")) if ment_root.is_dir() else []

    counts: dict[str, int] = defaultdict(int)
    stale: list[tuple[int, str, str]] = []  # (age_days, advisor, mention_id)

    for f in open_files:
        advisor = f.parent.parent.name
        counts[advisor] += 1

        mention_id = f.stem
        created = fm_get(f, "created") or ""
        created_day = created[:10]
        if re.match(r"^\d{4}-\d{2}-\d{2}$", created_day):
            try:
                created_date = _date_cls.fromisoformat(created_day)
                age_days = (now_date - created_date).days
                if age_days > 14:
                    stale.append((age_days, advisor, mention_id))
            except ValueError:
                pass

    # --- Open mention counts per recipient (advisor ASC) ---
    parts.append("## Open mentions\n")
    parts.append("\n")
    if counts:
        for advisor in sorted(counts):
            parts.append(f"- {advisor}: {counts[advisor]}\n")
    else:
        parts.append("- _(none)_\n")
    parts.append("\n")

    # --- Stale mentions (open > 14 days), sorted age DESC ---
    parts.append("## Stale mentions (open > 14 days)\n")
    parts.append("\n")
    if stale:
        stale.sort(key=lambda x: x[0], reverse=True)
        for age_days, advisor, mention_id in stale:
            parts.append(
                f"- [{mention_id}](mentions/{advisor}/open/{mention_id}.md)"
                f" — {age_days} days old\n"
            )
    else:
        parts.append("- _(none)_\n")
    parts.append("\n")

    snapshot_write(out, "".join(parts))
    return out
